Name:           ros-kinetic-genpy
Version:        0.6.6
Release:        0
Summary:        ROS genpy package
Group:          Development/Libraries
License:        BSD
Source0:        %{name}-%{version}.tar.gz
Source1001:     %{name}.manifest
BuildRequires:  gcc-c++
BuildRequires:  ros-kinetic-catkin
BuildRequires:  ros-kinetic-genmsg
Requires:       ros-kinetic-genmsg
Requires:       python-PyYAML

%define         src_name genpy

%description
Python ROS message and service generators.

%prep
%setup -q
cp %{SOURCE1001} .

%build
%{__ros_setup}
%{__ros_build}

%install
%{__ros_setup}
%{__ros_install}

%files -f build/install_manifest.txt
%manifest %{name}.manifest
%defattr(-,root,root)
%{__ros_install_path}/lib/python2.7/site-packages/*

%changelog
* Fri May 09 2014 Dirk Thomas <dthomas@osrfoundation.org> - 0.4.14-0
- Autogenerated by Bloom
